#!/opt/anaconda3/bin/python3
from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import textwrap
import time
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SERVER = ROOT / "scripts" / "codex_reviewer_mcp.py"
PROTOCOL_VERSION = "2025-06-18"


def send(process: subprocess.Popen[str], payload: dict) -> None:
    raw = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    header = f"Content-Length: {len(raw)}\r\n\r\n".encode("utf-8")
    assert process.stdin is not None
    process.stdin.buffer.write(header)
    process.stdin.buffer.write(raw)
    process.stdin.flush()


def receive(process: subprocess.Popen[str]) -> dict:
    assert process.stdout is not None
    headers: dict[str, str] = {}
    while True:
        line = process.stdout.buffer.readline()
        if not line:
            raise RuntimeError("MCP server closed stdout unexpectedly")
        if line in (b"\r\n", b"\n"):
            break
        key, value = line.decode("utf-8").split(":", 1)
        headers[key.lower()] = value.strip()

    content_length = int(headers["content-length"])
    body = process.stdout.buffer.read(content_length)
    return json.loads(body.decode("utf-8"))


def write_fake_codex(path: Path) -> None:
    path.write_text(
        textwrap.dedent(
            """\
            #!/usr/bin/env python3
            from __future__ import annotations

            import json
            import os
            import re
            import sys
            import time
            from pathlib import Path


            def main() -> int:
                args = sys.argv[1:]
                if not args or args[0] != "exec":
                    return 2
                is_resume = len(args) > 1 and args[1] == "resume"
                prompt = args[-1] if args else ""
                output_path = None
                for index, value in enumerate(args):
                    if value in {"-o", "--output-last-message"} and index + 1 < len(args):
                        output_path = Path(args[index + 1])
                        break

                conversation_id = args[-2] if is_resume else os.environ.get("FAKE_THREAD_ID", "thread-fake")
                delay = float(os.environ.get("FAKE_CODEX_DELAY", "0.6"))
                time.sleep(delay)

                artifact_match = re.search(r"本轮优先产物路径：((?:\\./)?\\.codex/[A-Za-z0-9._/-]+)", prompt)
                if artifact_match:
                    artifact_path = Path(artifact_match.group(1).removeprefix("./"))
                else:
                    matches = re.findall(r"(?:\\./)?(\\.codex/[A-Za-z0-9._/-]+)", prompt)
                    artifact_path = Path(matches[-1]) if matches else None

                if artifact_path is not None:
                    target = Path.cwd() / artifact_path
                    target.parent.mkdir(parents=True, exist_ok=True)
                    target.write_text(f"generated by fake codex for {artifact_path.name}\\n", encoding="utf-8")

                if output_path is not None:
                    output_path.parent.mkdir(parents=True, exist_ok=True)
                    output_path.write_text("fake assistant message", encoding="utf-8")

                print(json.dumps({"thread_id": conversation_id}))
                return 0


            if __name__ == "__main__":
                raise SystemExit(main())
            """
        ),
        encoding="utf-8",
    )
    path.chmod(0o755)


def wait_for_job_completion(process: subprocess.Popen[str], cwd: Path, job_id: str, timeout_seconds: float = 10.0) -> dict:
    deadline = time.monotonic() + timeout_seconds
    last_payload: dict | None = None
    while time.monotonic() < deadline:
        send(
            process,
            {
                "jsonrpc": "2.0",
                "id": 90,
                "method": "tools/call",
                "params": {
                    "name": "review_status",
                    "arguments": {
                        "cwd": str(cwd),
                        "job_id": job_id,
                    },
                },
            },
        )
        last_payload = receive(process)["result"]["structuredContent"]
        if last_payload["status"] in {"completed", "error", "timeout", "stale", "failed"}:
            return last_payload
        time.sleep(0.1)
    raise AssertionError(f"review job {job_id} did not finish in time; last payload={last_payload}")


def main() -> int:
    fake_dir = Path(tempfile.mkdtemp(prefix="fake-codex-bin-"))
    fake_codex = fake_dir / "codex-fake.py"
    write_fake_codex(fake_codex)
    base_env = {
        **os.environ,
        "CODEX_REVIEWER_FRAMEWORK_ROOT": str(ROOT),
        "CODEX_BINARY": str(fake_codex),
        "FAKE_THREAD_ID": "thread-initial",
        "FAKE_CODEX_DELAY": "0.6",
    }

    process = subprocess.Popen(
        [sys.executable, str(SERVER)],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        cwd=str(ROOT),
        env=base_env,
    )

    try:
        send(
            process,
            {
                "jsonrpc": "2.0",
                "id": 1,
                "method": "initialize",
                "params": {
                    "protocolVersion": PROTOCOL_VERSION,
                    "capabilities": {"elicitation": {}, "roots": {}, "sampling": {}},
                    "clientInfo": {"name": "smoke", "version": "0.1.0"},
                },
            },
        )
        initialize_response = receive(process)
        assert initialize_response["result"]["serverInfo"]["name"] == "codex-reviewer-wrapper"
        assert initialize_response["result"]["protocolVersion"] == PROTOCOL_VERSION
        assert initialize_response["result"]["capabilities"]["tools"]["listChanged"] is False

        send(process, {"jsonrpc": "2.0", "method": "notifications/initialized", "params": {}})

        send(process, {"jsonrpc": "2.0", "id": 2, "method": "resources/list", "params": {}})
        resources_response = receive(process)
        assert resources_response["result"]["resources"] == []

        send(process, {"jsonrpc": "2.0", "id": 3, "method": "resources/templates/list", "params": {}})
        resource_templates_response = receive(process)
        assert resource_templates_response["result"]["resourceTemplates"] == []

        send(process, {"jsonrpc": "2.0", "id": 4, "method": "tools/list", "params": {}})
        tools_response = receive(process)
        tool_names = {tool["name"] for tool in tools_response["result"]["tools"]}
        assert {"codex", "codex_reply", "review_gate", "review_status"} <= tool_names

        send(
            process,
            {
                "jsonrpc": "2.0",
                "id": 5,
                "method": "tools/call",
                "params": {
                    "name": "codex",
                    "arguments": {
                        "prompt": "[TASK_MARKER: 20260323-120000-ABCD]\n请做上下文扫描。",
                        "cwd": str(ROOT),
                        "artifact_path": ".codex/context-initial.json",
                        "dry_run": True,
                    },
                },
            },
        )
        dry_run_response = receive(process)
        payload = dry_run_response["result"]["structuredContent"]
        assert payload["status"] == "dry_run"
        assert payload["task_marker"] == "20260323-120000-ABCD"
        assert payload["artifact_path"] == ".codex/context-initial.json"
        assert payload["documents"]["chosen_agents"]
        assert payload["documents"]["chosen_main"]
        assert payload["documents"]["chosen_agents"].endswith("/.codex/AGENTS.md")
        assert payload["documents"]["chosen_main"].endswith("/.codex/CODEX.md")
        assert payload["command"][1] == "exec"

        with tempfile.TemporaryDirectory(prefix="async-reviewer-smoke-") as temp_dir:
            repo_root = Path(temp_dir)

            send(
                process,
                {
                    "jsonrpc": "2.0",
                    "id": 6,
                    "method": "tools/call",
                    "params": {
                        "name": "codex",
                        "arguments": {
                            "prompt": "[TASK_MARKER: 20260323-120001-ASYNC]\n请做上下文扫描。",
                            "cwd": str(repo_root),
                            "artifact_path": ".codex/context-initial.json",
                            "timeout_seconds": 30,
                        },
                    },
                },
            )
            queued_payload = receive(process)["result"]["structuredContent"]
            assert queued_payload["status"] == "queued"
            assert queued_payload["job_id"]
            assert queued_payload["task_marker"] == "20260323-120001-ASYNC"
            first_job_id = queued_payload["job_id"]

            send(
                process,
                {
                    "jsonrpc": "2.0",
                    "id": 7,
                    "method": "tools/call",
                    "params": {
                        "name": "codex",
                        "arguments": {
                            "prompt": "[TASK_MARKER: 20260323-120001-ASYNC]\n请做上下文扫描。",
                            "cwd": str(repo_root),
                            "artifact_path": ".codex/context-initial.json",
                            "timeout_seconds": 30,
                        },
                    },
                },
            )
            reused_payload = receive(process)["result"]["structuredContent"]
            assert reused_payload["reused_existing_job"] is True
            assert reused_payload["job_id"] == first_job_id

            completed_initial = wait_for_job_completion(process, repo_root, first_job_id)
            assert completed_initial["status"] == "completed"
            assert completed_initial["artifact_exists"] is True
            assert completed_initial["conversation_id"] == "thread-initial"
            assert (repo_root / ".codex" / "context-initial.json").exists()

            send(
                process,
                {
                    "jsonrpc": "2.0",
                    "id": 8,
                    "method": "tools/call",
                    "params": {
                        "name": "review_status",
                        "arguments": {
                            "cwd": str(repo_root),
                            "task_marker": "[TASK_MARKER: 20260323-120001-ASYNC]",
                        },
                    },
                },
            )
            status_by_marker = receive(process)["result"]["structuredContent"]
            assert status_by_marker["job_id"] == first_job_id

            send(
                process,
                {
                    "jsonrpc": "2.0",
                    "id": 9,
                    "method": "tools/call",
                    "params": {
                        "name": "codex_reply",
                        "arguments": {
                            "conversation_id": completed_initial["conversation_id"],
                            "prompt": "[TASK_MARKER: 20260323-120001-ASYNC-REPLY]\nWrite ./.codex/review-report.md after continuing the review.",
                            "cwd": str(repo_root),
                            "artifact_path": ".codex/review-report.md",
                            "timeout_seconds": 30,
                        },
                    },
                },
            )
            queued_reply = receive(process)["result"]["structuredContent"]
            assert queued_reply["status"] == "queued"
            second_job_id = queued_reply["job_id"]

            completed_reply = wait_for_job_completion(process, repo_root, second_job_id)
            assert completed_reply["status"] == "completed"
            assert completed_reply["artifact_exists"] is True
            assert completed_reply["conversation_id"] == "thread-initial"
            assert (repo_root / ".codex" / "review-report.md").exists()

            send(
                process,
                {
                    "jsonrpc": "2.0",
                    "id": 10,
                    "method": "tools/call",
                    "params": {
                        "name": "review_gate",
                        "arguments": {
                            "cwd": str(repo_root),
                            "conversation_id": completed_reply["conversation_id"],
                            "artifact_path": ".codex/review-report.md",
                            "allow_local_fallback": False,
                        },
                    },
                },
            )
            remote_gate = receive(process)["result"]["structuredContent"]
            assert remote_gate["gate_passed"] is True
            assert remote_gate["review_mode"] == "mcp"

        with tempfile.TemporaryDirectory(prefix="review-gate-smoke-") as temp_dir:
            repo_root = Path(temp_dir)
            artifact_path = repo_root / ".codex" / "review-report.md"
            artifact_path.parent.mkdir(parents=True, exist_ok=True)

            send(
                process,
                {
                    "jsonrpc": "2.0",
                    "id": 11,
                    "method": "tools/call",
                    "params": {
                        "name": "review_gate",
                        "arguments": {
                            "cwd": str(repo_root),
                            "artifact_path": ".codex/review-report.md",
                            "allow_local_fallback": True,
                        },
                    },
                },
            )
            blocked_response = receive(process)["result"]["structuredContent"]
            assert blocked_response["gate_passed"] is False
            assert blocked_response["blocking_reason"] == "review_artifact_missing"

            artifact_path.write_text("# review\n", encoding="utf-8")
            send(
                process,
                {
                    "jsonrpc": "2.0",
                    "id": 12,
                    "method": "tools/call",
                    "params": {
                        "name": "review_gate",
                        "arguments": {
                            "cwd": str(repo_root),
                            "artifact_path": ".codex/review-report.md",
                            "allow_local_fallback": True,
                        },
                    },
                },
            )
            passed_response = receive(process)["result"]["structuredContent"]
            assert passed_response["gate_passed"] is True
            assert passed_response["review_mode"] == "local_fallback"
            assert passed_response["artifact_exists"] is True

        doctor_result = subprocess.run(
            [sys.executable, str(SERVER), "doctor", "--cwd", str(ROOT), "--json"],
            check=False,
            capture_output=True,
            text=True,
            env=base_env,
        )
        assert doctor_result.returncode in {0, 1}
        doctor_payload = json.loads(doctor_result.stdout)
        assert doctor_payload["status"] in {"ok", "warn"}
        assert doctor_payload["wrapper_health"]["server_name"] == "codex-reviewer-wrapper"
        assert doctor_payload["wrapper_health"]["protocol_version"] == PROTOCOL_VERSION
        assert "review_gate" in doctor_payload["wrapper_health"]["tools"]

        probe_result = subprocess.run(
            [sys.executable, str(SERVER), "probe", "--json"],
            check=False,
            capture_output=True,
            text=True,
            env=base_env,
        )
        assert probe_result.returncode == 0
        probe_payload = json.loads(probe_result.stdout)
        assert probe_payload["status"] == "ok"
        assert probe_payload["protocol_version"] == PROTOCOL_VERSION
        assert probe_payload["initialize_response_protocol"] == PROTOCOL_VERSION
        assert {"codex", "codex_reply", "review_gate", "review_status"} <= set(probe_payload["tool_names"])

        with tempfile.TemporaryDirectory(prefix="reviewer-log-smoke-") as temp_dir:
            log_path = Path(temp_dir) / "codex-reviewer.log"
            logged_env = {**base_env, "CODEX_REVIEWER_LOG_PATH": str(log_path)}
            logged_probe = subprocess.run(
                [sys.executable, str(SERVER), "probe", "--json"],
                check=False,
                capture_output=True,
                text=True,
                env=logged_env,
            )
            assert logged_probe.returncode == 0
            log_text = log_path.read_text(encoding="utf-8")
            assert "received_method" in log_text
            assert "initialize" in log_text
            assert "tools_list" in log_text

        with tempfile.TemporaryDirectory(prefix="review-gate-cli-") as temp_dir:
            repo_root = Path(temp_dir)
            report_path = repo_root / ".codex" / "review-report.md"
            report_path.parent.mkdir(parents=True, exist_ok=True)

            failed_gate = subprocess.run(
                [
                    sys.executable,
                    str(SERVER),
                    "review-gate",
                    "--cwd",
                    str(repo_root),
                    "--artifact-path",
                    ".codex/review-report.md",
                    "--json",
                ],
                check=False,
                capture_output=True,
                text=True,
                env=base_env,
            )
            assert failed_gate.returncode == 2

            report_path.write_text("# review\n", encoding="utf-8")
            passed_gate = subprocess.run(
                [
                    sys.executable,
                    str(SERVER),
                    "review-gate",
                    "--cwd",
                    str(repo_root),
                    "--artifact-path",
                    ".codex/review-report.md",
                    "--json",
                ],
                check=False,
                capture_output=True,
                text=True,
                env=base_env,
            )
            assert passed_gate.returncode == 0
            gate_payload = json.loads(passed_gate.stdout)
            assert gate_payload["gate_passed"] is True
            assert gate_payload["review_mode"] == "local_fallback"

        print("smoke test passed")
        return 0
    finally:
        process.terminate()
        try:
            process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait(timeout=5)


if __name__ == "__main__":
    raise SystemExit(main())
